package com.github.ttftcuts.gigatools.main.util

import com.intellij.openapi.util.TextRange

object TextUtils {
    fun StringBuilder.appendGeneratedFileWarning() {
        appendLine("# WARNING:")
        appendLine("# The contents of this file are generated by script. Any edits will be overwritten.")
        appendLine()
    }

    fun StringBuilder.appendGeneratedLocFileWarning() {
        appendLine(" # WARNING:")
        appendLine(" # The english version of this file is generated by script. Any edits will be overwritten.")
        appendLine()
    }

    fun StringBuilder.appendEOFComment() {
        appendLine("# EOF")
    }

    fun StringBuilder.appendSectionBreak() {
        appendLine()
        appendLine("#".repeat(120))
        appendLine("#".repeat(120))
        appendLine("#".repeat(120))
        appendLine()
    }

    fun range(range: IntRange): TextRange = TextRange.create(range.first, range.last+1)
}