package com.github.ttftcuts.gigatools.main.util

object TextUtils {
    fun StringBuilder.appendGeneratedFileWarning() {
        appendLine("# WARNING:")
        appendLine("# The contents of this file are generated by script. Any edits will be overwritten.")
        appendLine()
    }

    fun StringBuilder.appendGeneratedLocFileWarning() {
        appendLine(" # WARNING:")
        appendLine(" # The english version of this file is generated by script. Any edits will be overwritten.")
        appendLine()
    }

    fun StringBuilder.appendEOFComment() {
        appendLine("# EOF")
    }
}