package com.github.ttftcuts.gigatools.main.data

import com.github.ttftcuts.gigatools.main.lists.ListFormat
import com.github.ttftcuts.gigatools.main.definitions.DefinitionTag
import com.github.ttftcuts.gigatools.main.util.YAMLUtils.getValueAndCast
import com.github.ttftcuts.gigatools.main.util.YAMLUtils.resolveKeyValues
import com.intellij.openapi.application.readAction
import com.intellij.openapi.project.Project
import com.intellij.psi.PsiManager
import com.intellij.psi.search.FilenameIndex
import com.intellij.psi.search.GlobalSearchScope
import org.jetbrains.yaml.psi.YAMLFile
import org.jetbrains.yaml.psi.YAMLMapping
import org.jetbrains.yaml.psi.YAMLScalar
import org.jetbrains.yaml.psi.YAMLSequence

object ToolData {
    suspend fun loadDataFile(project: Project, initialLoad: Boolean = false) {
        readAction {
            isLoaded = false // clear here so if anything fails it remains false
            val files = FilenameIndex.getVirtualFilesByName("gigatools_data.yml", GlobalSearchScope.projectScope(project))
            if (files.isEmpty()) {
                if (initialLoad) {
                    return@readAction
                }
                error("Data file not found")
            }
            val psiFile = PsiManager.getInstance(project).findFile(files.first())
            if (psiFile !is YAMLFile) {
                error("Data file isn't YAML")
            }

            val rootElement = psiFile.documents.first().topLevelValue
            if (rootElement !is YAMLMapping) {
                error("Malformed data file, should be a map at root")
            }
            val root: YAMLMapping = rootElement

            // oh boy this is a complex line
            // for each pair in the tags element's key-value pairs, make a map of the key text and a map of the value's key-value pairs, mapped to THEIR name and a tag entry derived from the value
            definitionTags = root.getValueAndCast<YAMLMapping>("tags").resolveKeyValues().associate { categoryPair ->
                categoryPair.keyText to categoryPair.getValueAndCast<YAMLMapping>().resolveKeyValues().associate { entryPair ->
                    entryPair.keyText to DefinitionTag.fromYAMLKeyValue(entryPair)
                }
            }

            // get all the list formats too!
            listFormats = root.getValueAndCast<YAMLMapping>("list_formats").resolveKeyValues().associate { pair ->
                pair.keyText to ListFormat.fromYAMLKeyValue(pair)
            }

            // mega family data - name and ancestor overrides
            MegaFamilies.ancestorOverrides = root.getValueAndCast<YAMLMapping>("mega_families").getValueAndCast<YAMLMapping>("ancestor_overrides").resolveKeyValues().associate {
                pair -> pair.keyText to pair.valueText
            }
            MegaFamilies.nameOverrides = root.getValueAndCast<YAMLMapping>("mega_families").getValueAndCast<YAMLMapping>("name_overrides").resolveKeyValues().associate { pair ->
                pair.keyText to pair.valueText
            }

            // economic category loc, categories to include and exclude, resources to exclude
            EcoCategoryLoc.includeCategories =
                root.getValueAndCast<YAMLMapping>("eco_category_loc").getValueAndCast<YAMLMapping>("categories")
                    .getValueAndCast<YAMLSequence>("include").items.map { item -> item.getValueAndCast<YAMLScalar>().textValue }
                    .toSet()
            EcoCategoryLoc.excludeCategories =
                root.getValueAndCast<YAMLMapping>("eco_category_loc").getValueAndCast<YAMLMapping>("categories")
                    .getValueAndCast<YAMLSequence>("exclude").items.map { item -> item.getValueAndCast<YAMLScalar>().textValue }
                    .toSet()
            EcoCategoryLoc.excludeResources =
                root.getValueAndCast<YAMLMapping>("eco_category_loc").getValueAndCast<YAMLMapping>("resources")
                    .getValueAndCast<YAMLSequence>("exclude").items.map { item -> item.getValueAndCast<YAMLScalar>().textValue }
                    .toSet()

            isLoaded = true // we made it! loaded!
        }
    }

    var isLoaded: Boolean = false
        private set

    const val textGeneratedBlock = "WARNING: The contents of this block are generated by script, any manual changes will be overwritten"

    lateinit var definitionTags: Map<String,Map<String, DefinitionTag>>
    fun getTagsForType(type: String) : Map<String, DefinitionTag> {
        return definitionTags[type] ?: emptyMap()
    }
    lateinit var listFormats: Map<String, ListFormat>

    object MegaFamilies {
        lateinit var ancestorOverrides: Map<String, String>
        lateinit var nameOverrides: Map<String, String>
    }

    object EcoCategoryLoc {
        lateinit var includeCategories: Set<String>
        lateinit var excludeCategories: Set<String>
        lateinit var excludeResources: Set<String>
    }
}