package com.github.ttftcuts.gigatools.main.definitions.properties

import com.github.ttftcuts.gigatools.main.data.Consts
import com.github.ttftcuts.gigatools.main.definitions.Definition
import com.github.ttftcuts.gigatools.main.definitions.DefinitionHolder
import com.github.ttftcuts.gigatools.main.definitions.PropertyCompanion
import com.github.ttftcuts.gigatools.main.wrappers.WrapperCompanion
import icu.windea.pls.script.psi.ParadoxScriptDefinitionElement
import kotlin.reflect.full.companionObject

class TaggedListGeneratorProperty<T: Definition>(override val def: ParadoxScriptDefinitionElement, defType: WrapperCompanion<T>): DefinitionHolder, ITaggedListGeneratorProperty<T> {

    override val taggedListInfo by lazy {
        val data = Definition.getAttachedProperties(def).firstOrNull { p -> p.type == TaggedListGeneratorProperty }
        if (data == null) { return@lazy null }

        TaggedListInfo(defType)
    }

    companion object: PropertyCompanion("TaggedList", "Mark this trigger/effect as a generated list of tag-holding objects, regenerated by command.") {
        override fun validForDefinitionType(type: String): Boolean {
            return type == "scripted_trigger" || type == "scripted_effect"
        }
    }
}

interface ITaggedListGeneratorProperty<T: Definition>: DefinitionHolder {
    val taggedListInfo: TaggedListInfo<T>?
}

class TaggedListInfo<T: Definition>(val defType: WrapperCompanion<T>)