package com.github.ttftcuts.gigatools.main.definitions.properties

import com.github.ttftcuts.gigatools.main.data.Consts
import com.github.ttftcuts.gigatools.main.data.ToolData
import com.github.ttftcuts.gigatools.main.definitions.Definition
import com.github.ttftcuts.gigatools.main.definitions.DefinitionHolder
import com.github.ttftcuts.gigatools.main.definitions.PropertyCompanion
import com.github.ttftcuts.gigatools.main.lists.ListFormat
import com.github.ttftcuts.gigatools.main.wrappers.WrapperCompanion
import icu.windea.pls.script.psi.ParadoxScriptDefinitionElement

class TaggedListGeneratorProperty(override val def: ParadoxScriptDefinitionElement): DefinitionHolder, ITaggedListGeneratorProperty {

    override val taggedListInfo by lazy {
        val data = Definition.getAttachedProperties(def).firstOrNull { p -> p.type == TaggedListGeneratorProperty }
        if (data == null) { return@lazy null }

        TaggedListInfo.parse(data.propertyText)
    }

    companion object: PropertyCompanion("TaggedList", "Mark this trigger/effect as a generated list of tag-holding objects, regenerated by command.") {
        override fun validForDefinitionType(type: String): Boolean {
            return type == "scripted_trigger" || type == "scripted_effect"
        }
    }
}

interface ITaggedListGeneratorProperty: DefinitionHolder {
    val taggedListInfo: TaggedListInfo?
}

class TaggedListInfo(val type: WrapperCompanion<*>, val template: ListFormat, val parameters: Map<String,String>) {

    companion object {
        val partsPattern by lazy { Regex("\\@(\\w+)\\(([^@]+)\\)") }
        val parameterPattern by lazy { Regex("(\\w+):\\s+(\\w+)")}

        fun parse(input: String): TaggedListInfo? {
            var type: WrapperCompanion<*>? = null
            var template: ListFormat? = null
            //var tags:
            val parameters: MutableMap<String,String> = mutableMapOf()

            val parts = partsPattern.findAll(input)

            println(parts.map { r -> r.value }.toList())

            for (part in parts) {
                val name = part.groups[1]?.value?.trim() ?: error("TaggedList part name match missing")
                val text = part.groups[2]?.value?.trim() ?: error("TaggedList part text match missing")
                when(name) {
                    "type" -> {
                        if (type == null) {
                            type = Consts.DefinitionTypes.find { type -> type.typeExpression == text }
                        } else {
                            error("TaggedList part 'type' already has a value")
                        }
                    }
                    "template" -> {
                        if (template == null) {
                            if (ToolData.listFormats.contains(text)) {
                                template = ToolData.listFormats[text]
                            } else {
                                error("TaggedList part 'template' references invalid List Format: $text")
                            }
                        } else {
                            error("TaggedList part 'template' already has a value")
                        }
                    }
                    "tags" -> {}
                    "parameters" -> {
                        val pairs = parameterPattern.findAll(text)
                        for (pair in pairs) {
                            val pName = pair.groups[1]?.value?.trim() ?: error("TaggedList parameter name match missing")
                            val pVal = pair.groups[2]?.value?.trim() ?: error("TaggedList parameter value match missing")

                            parameters[pName] = pVal
                        }
                    }
                    else -> error("TaggedList part unknown: $name")
                }
            }

            if ((type != null) && (template != null)) {
                return TaggedListInfo(type, template, parameters)
            }

            return null
        }
    }
}